### ISSUE TITLE
`config.yaml` is too verbose when TKGI API and creds are same for multiple clusters

### ISSUE THREAD

**Issue by jakuboskera** [jakuboskera/tkgi-kubectx#1]
Situation when you have e.g. 3 clusters and same TKGI API and creds for these clusters. In current `config.yaml` the structure is too verbose. Use new structure to reduce verbosity.

Current state

```yaml
clusters:
  - name: cluster1
    creds: jwick
    tkgiApi: https://tkgi.example.com
  - name: cluster2
    creds: jwick
    tkgiApi: https://tkgi.example.com
  - name: cluster3
    creds: jwick
    tkgiApi: https://tkgi.example.com
```

Proposal

```yaml
tkgi:
  - url: https://tkgi.example.com
    creds: jwick
    clusters:
      - cluster1
      - cluster2
      - cluster3
```
